In [1]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [2]:
true_w = torch.tensor([2,-3.4])
true_b = 4.2
features,labels = d2l.synthetic_data(true_w,true_b,1000)

In [5]:
def load_array(data_arrays,batch_size,is_train = True):
    dataset = data.TensorDataset(*data_arrays)  #*表示解包 即将数据展开
    return data.DataLoader(dataset,batch_size,shuffle=is_train)
batch_size = 10
data_iter = load_array((features,labels),batch_size)  #读取数据
next(iter(data_iter))   #测试迭代器是否正确

[tensor([[-0.2167,  0.0712],
         [ 0.7211,  0.5818],
         [-1.9676,  0.6724],
         [-0.2021,  0.2330],
         [-1.3901,  0.8319],
         [-1.9522, -0.7655],
         [-0.8998,  1.3311],
         [ 1.3012,  1.7173],
         [ 0.1623, -0.5272],
         [ 0.6399,  0.3006]]),
 tensor([[ 3.5382],
         [ 3.6639],
         [-2.0201],
         [ 2.9864],
         [-1.4171],
         [ 2.9140],
         [-2.1178],
         [ 0.9504],
         [ 6.3121],
         [ 4.4535]])]

In [6]:
from torch import nn
net = nn.Sequential(nn.Linear(2,1))  #确定输入：2和输出：1
#初始化模型参数
net[0].weight.data.normal_(0,0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [17]:
# 初始化模型参数
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)


tensor([0.])

In [7]:
#计算均方误差
loss = nn.MSELoss()
#定义优化算法SGD
trainer = torch.optim.SGD(net.parameters(),lr=0.04)
trainer

SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)

In [8]:
num_epochs = 5
for epoch in range(num_epochs):
    for X,y in data_iter:
        l = loss(net(X),y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
        # print(f'w:{net[0].weight.data},b:{net[0].bias.data}')
    l = loss(net(features),labels)
    print(f'epoch:{epoch+1},loss: {l:f}')

SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)
SGD (
Parameter Group 0
    dampening: 0
    foreach: None
    lr: 0.04
    maximize: False
    mome