In [2]:
import torch
x = torch.arange(4.0,requires_grad=True)
x.grad

In [5]:
x
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [6]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [8]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [16]:
x.grad.zero_()
y = x * x
print(y)
y.backward(torch.ones(len(x)))
x.grad
u = y.detach()
u


tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([0., 1., 4., 9.])

In [18]:
help(torch.normal)

Help on built-in function normal in module torch:

normal(...)
    normal(mean, std, *, generator=None, out=None) -> Tensor
    
    Returns a tensor of random numbers drawn from separate normal distributions
    whose mean and standard deviation are given.
    
    The :attr:`mean` is a tensor with the mean of
    each output element's normal distribution
    
    The :attr:`std` is a tensor with the standard deviation of
    each output element's normal distribution
    
    The shapes of :attr:`mean` and :attr:`std` don't need to match, but the
    total number of elements in each tensor need to be the same.
    
    .. note:: When the shapes do not match, the shape of :attr:`mean`
              is used as the shape for the returned output tensor
    
    .. note:: When :attr:`std` is a CUDA tensor, this function synchronizes
              its device with the CPU.
    
    Args:
        mean (Tensor): the tensor of per-element means
        std (Tensor): the tensor of per-element st

In [3]:
import torch
a = torch.tensor([3,-2])
b = torch.tensor([[5,4],[3,2],[2,3]])
print(a.shape)
print(b.shape)
print(torch.matmul(b,a),torch.matmul(b,a).shape)

torch.Size([2])
torch.Size([3, 2])
tensor([7, 5, 0]) torch.Size([3])


In [5]:
a = torch.randn(4,4)
b = a + a.T
print(b == b.T)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [4]:
import torch
import random
a = torch.tensor([10,2,5,6,3,4,5])
indices = list(range(5))
random.shuffle(indices)
print(indices)
indices_batch = indices[0:5]
a[indices_batch]

[2, 4, 0, 1, 3]


tensor([ 5,  3, 10,  2,  6])